### ISSUE TITLE
Proposal to fix RHEL-07-040600 For Red Hat Enterprise Linux operating systems using DNS resolution, at least two name servers must be configured.

### ISSUE THREAD

**Issue by juliedavila** [ansible-lockdown/RHEL7-STIG#193]
I think we can make this fixable. Here's what I propose

1) After confirming that DNS name resolution is being used, we default to Google's DNS nameservers but of course allow for end users to provide a list variable of DNS servers to use instead
2) In the event of local host auth, we can ensure that resolv.conf is empty

### Check Text

Determine whether the system is using local or DNS name resolution with the following command:  
`# grep hosts /etc/nsswitch.conf`  

If the DNS entry is missing from the host's line in the `/etc/nsswitch.conf` file, the `/etc/resolv.conf` file must be empty.  

Verify the "/etc/resolv.conf" file is empty with the following command:  
`# ls -al /etc/resolv.conf -rw-r--r--  1 root root        0 Aug 19 08:31 resolv.conf`
 
If local host authentication is being used and the `/etc/resolv.conf` file is not empty, this is a finding.  If the DNS entry is found on the host's line of the `/etc/nsswitch.conf` file, verify the operating system is configured to use two or more name servers for DNS resolution.  
Determine the name servers used by the system with the following command: 
` # grep nameserver /etc/resolv.conf nameserver` 
If less than two lines are returned that are not commented out, this is a finding.

**Comment by shepdelacreme** [comment]
This seems like the correct course of action to me. The only issue I ran into with the DNS thing was that it required 2 nameservers which breaks in AWS environments. Also I'm not sure what this means for folks who are getting their DNS from DHCP.  Setting the immutable flag as detailed at the bottom of that Fix text seems like overkill and would definitely break dynamic environments.

**Comment by jamescassell** [comment]
I would want to check if there's an existing DNS server and keep that rather than point to Google. Also, if the check doesn't fail for not having immutable, I would skip that step, as that should be a deliberate administrator action and not touched by automation IMHO.

**Comment by defionscode** [comment]
Yeah I wouldnt want to clobber something that exists. The tricky part becomes what do we do if it's only one server listed? Or it's dynamic? Maybe we do a custom error message?

**Comment by shepdelacreme** [comment]
The check doesn't explicitly fail for not having immutable but it does have a note about a having a documented exception:

> If the "/etc/resolv.conf" file must be mutable, the required configuration must be documented with the Information System Security Officer (ISSO) and the file must be verified by the system file integrity tool.

**Comment by shepdelacreme** [comment]
It becomes tricky to leave exiting settings since most systems are going to have "something" in their when this role is run. They will need it to having a functioning network connection.

Maybe this becomes one of those rules that people need to disable if they don't want it to clobber their existing settings with whatever is set in the nameserver vars?

**Comment by jamescassell** [comment]
If we do end up setting the immutable flag we should definitely not put any workarounds to unset it if the role would otherwise change the file. In that case, we might set ignore errors yes on the task. If it the administrator set a file as immutable we should absolutely respect that setting.

**Comment by shepdelacreme** [comment]
Yeah...I'm wondering how Ansible will fail if the file is immutable. It might be nice to have a custom failed_when instead of just ignoring errors. That or check for the immutable flag first and skip the task if it is immutable.

**Comment by jamescassell** [comment]
Ansible will fail with permission denied

**Comment by BryanJeterAL** [comment]
Read the Fix Text for this finding.  It requires "local authoritative name servers".  Best approach would be requiring minimum of two of these in the role variables.  Setting them to an arbitrary external PUBLIC name server will not go over well in DoD organizations.  The check should use `grep -c ^nameserver /etc/resolv.conf` to count number of uncommented nameserver lines.  (added '-c' to count, and '^' to capture only lines beginning with the word nameserver (not #nameserver).

DISA's check using `ls` looking for size zero files is a bad check too, since the file can begin with `#created by anaconda` even if there is no uncommented nameserver, so hopefully the task here does something with grep or awk.

**Comment by jamescassell** [comment]
it's interesting how they put what sound like requirements in the "Fix Text" section:

> If the "/etc/resolv.conf" file must be mutable, the required configuration must be documented with the Information System Security Officer (ISSO) and the file must be verified by the system file integrity tool.

I've always thought of that section as irrelevant to compliance.  Perhaps a question for the disa help line: disa.stig_spt@mail.mil

If we're fixing this one, I'd be in favor of using rhel-system-roles/network to implement the fix, since it generically solves network config issues.  Otherwise, configure the nameservers in /etc/sysconfig/network-scripts/...  Don't configure /etc/resolv.conf directly since it will be overwritten. (Hence the suggestion to chattr +i)

**Comment by jamescassell** [comment]
I think that in the default mode, we should just warn if there are not two DNS servers configured.  Otherwise, I re-iterate my recommendation of using rhel-system-roles/network to do the actual config as that role is fully supported by Red Hat.  There are other common cases to consider, such as having a local dnsmasq configured in the /etc/resolv.conf (only one `127.0.0.1` exists, but I suppose we could add `::1` as well) and the dnsmasq forwards lookups as necessary to the actual DNSN server(s)

**Comment by shepdelacreme** [comment]
I agree with just making this a warning. There are many instances where having two DNS servers is not relevant.

**Comment by jamescassell** [comment]
V2R7 adds "If the file is mutable and has not been documented with the Information System Security Officer (ISSO), this is a finding." meaning that folks need to document if they want mutable /etc/resolv.conf

**Comment by georgenalen** [comment]
Hello,
I wanted to reach out and let you know that this issue is being closed. We have re-worked the role and want to start with a fresh issues list with this latest version. There was a post in the Ansible-Lockdown google group (https://groups.google.com/g/ansible-lockdown) with the details of the changes that are coming. Please checkout the thread titled RHEL 7 CIS and STIG Changes for all of the details, I also have the message pasted at below.
Please as you use the latest version and open issue tickets as you find them, it is the best way for us to improve the role for everyone. Thank you for being part of the community and providing awareness of problems or advice on improvement. Reporting is a huge part of improving this project.

--------------------------------
Hello,
Thank you to everyone in the Ansible-Lockdown community who has contributed to RHEL7 STIG/CIS. Our team at MindPoint Group has been working with the entirety of the Ansible-Lockdown project, and we have some significant updates for both RHEL 7 STIG and CIS. With these updates, some larger changes have been made. I have these changes/updates outlined below.
Testing:
1.	CI/CD - We have implemented some automated testing pipelines to test pull requests into the devel and main branches. With the current workflow, the community will PR into the devel branch (never the main branch) for review by the administrators. When your PR is created, the first check will remain the DCO check. The second check is a functional testing pipeline that will automatically perform a functional test of the branch the PR is initiated from. Once both tests pass, someone from the Administrator Team will review the changes and merge them into the devel branch. From there, an additional review is completed before the devel branch is merged into the main branch. Only the Admin Team will perform PRs/merges into the main branch. There is also an automated pipeline for PRs from devel to main. Please do not edit the .github/workflows files since those are used as part of the pipeline.
2.	Compliance Checking – MindPoint Group has been working to create our own compliance audit scan tool. The tool uses a goss framework executable to run custom checks that we have created. The goal is to provide a more thorough check for control compliance and decrease the number of false positives/negatives. For example, it will check the configuration file related to the control and as well as checking if that configuration is active. With a smarter scan, we can hopefully identify attempts to trick scanners as well (for example stacking a parameter in a config file where the first instance is enabled and second disabled. Most audit tools search for the first instance but the application might look for the last instance of the parameter, thus making the scanning tool think it's enabled). In testing, we have found that our audit scan runs significantly faster than other audit tools, reducing audit times. Our audit tool and profiles will have their own repositories in the Ansible-Lockdown org, but within the remediation role there will be an integrated way to incorporate the audit. Keep an eye out for the audit tools as they are released. We plan on developing a goss audit profile for each current remediation role. Going forward, we plan to release a remediation role and goss audit tool profile simultaneously.
Role Updates:
1.	RHEL 7 STIG/CIS – We have re-written much of the RHEL 7 STIG and CIS roles to increase clarity and readability and address some functionality items. We performed these updates while creating our goss testing framework for each of these roles. We plan on pushing our update to the devel and main branches. We will move the current devel and master branches to a devel_stable_ and master_stable_ branch in the respective repositories. Accordingly, community members who rely on the current version can still use that version going forward; this process will not remove what is currently there. The latest versions of the roles have also been updated to comply with the latest benchmarks.
2.	Role Architecture – All roles will change with regard to the structure in the tasks folder. Taking CIS as an example, there will be a folder per section and yaml files for each sub-section. For example control 1.2.1 in CIS will be located in RHEL7-CIS/tasks/section_1/cis_1.2.x.yml. The cis_1.2.x.yml file will contain all controls related to section 1.2.x. This will hopefully make updates to roles a bit easier with less risk. This matches the architecture of our audit tool, creating consistency across remediation and audit platforms. The end goal is to repeat this architecture (the best we can) on STIG roles, but we are starting with CIS.
3.	Existing PRs and Issues – With all of these changes comes the task of cleaning up existing PR’s and issues. Our plan is to close all of the existing PR’s and issues because of the re-work. Our team is growing and should be able to stay on top of the new issues and PRs as they come in.
Again, I would like to thank the community for your involvement in this project. The input and work from the community has contributed significantly to the success of this project. Please keep an eye out for these changes, which will be rolling out in the coming weeks.
