### ISSUE TITLE
Style/coding guidelines?

### ISSUE THREAD

**Issue by mikerenfro** [ansible-lockdown/RHEL7-STIG#81]
Starting point for how tasks should be organized before a 1.0 release.

Things I'm assuming:

- prelim.yml contains audit checks relevant to multiple tasks
- audit-cat[123].yml files get deprecated, content mostly moved to fix-cat[123].yml
- fix-cat[123].yml files contain blocks with audit and patch tasks, so that the same tags and when conditions can be applied to both tasks
- registers for audit tasks named `rhel_07_NNNNNN_audit`
- `result` registers for `lineinfile` and related file modification tasks use `result | failed` and `result.rc != 257` when files are missing (rsyslog, for example).

A Wiki page could be good for this, too, but no idea about how that gets set up.

**Comment by jamescassell** [comment]
These might be helpful:

- https://github.com/ansible/ansible-lockdown/blob/master/CONTRIBUTING.md
- https://github.com/shepdelacreme/benchparse

**Comment by mikerenfro** [comment]
They are. Thanks.

**Comment by shepdelacreme** [comment]
@mikerenfro Most of your assumptions are correct. The CONTRIBUTING guide in ansible-lockdown is mostly accurate...it needs a few updates. Here are some specific answers though.

1. `prelim.yml` should be reserved for things that are required for multiple fix tasks. i.e. Looking in the prelim file now the ONLY one that really looks like it makes sense to remain there is the Install AIDE task since it affects 5 different STIG items. The other items can be moved to a `block` statement with their respective STIG tasks.

1. Yes for the audit-cat[123].yml content. As a note I believe everything that is needed from those files has already been migrated and those can be cleaned up completely. I have this as an action item that I will complete once I merge in all the other outstanding PRs.

1. Yes for your understanding of the fix-cat[123].yml files. This needs to be documented somewhere now that we are using `block` statements/etc. The CONTRIBUTING guide was written prior to `block` existing in Ansible and needs to be updated.

1. Yes for naming the registered results.

1. I tend to shy away from using `result` as the name since it is generic and can cause issues. If the result is not being used outside the task registering it then I think its fine. As for the `result.rc != 257` I'm not sure that is needed on every single `lineinfile` task. Just in specific use cases.

**Comment by jamescassell** [comment]
My preference would be name->block->task with name, but it seems that ansible 2.4 does not output the block name on running the role...

In my ideal world, the block name would have the item title from the STIG, and the task names would describe what sub steps are being done to meet the STIG title task.  I haven't tested if ansible 2.5 outputs the block name...

**Comment by mikerenfro** [comment]
Related to "result registers for lineinfile and related file modification tasks use `result | failed` and `result.rc != 257` when files are missing (rsyslog, for example)" and the aide.conf checks, I suppose we can replace those lines with `when: register_for_conf.stat.exists` ?

**Comment by shepdelacreme** [comment]
@jamescassell yes it depends on if Ansible prints the block name I suppose.

@mikerenfro Yes I think I prefer using stat. Either will work but when you have multiple tasks editing the same file and they all have custom `failed_when` lines it adds a lot of extra lines that aren't needed.

**Comment by jamescassell** [comment]
1. Regarding the block "name', it looks like ansible doesn't currently output the block name on running the tasks in a block.   This is for the same reason that 'with_items' is not supported on a block (and the workaround of using includes for looping on multiple items.)  I'd still prefer to have a name on the block for future compatibility and current readability.

2. Regarding auditing, I propose that running the role in check mode should show which remediations are needed and (to the extent possible) should show what changes will be made if run with '--diff'. 
The trivial case is built-in modules that already support '--check' and '--diff'.  The more complicated cases are ones needing 'command' and 'shell' tasks. To this end, audit tasks that check if a remediation is needed should show as "changed" if the audit task indicates a change is needed, since the associated patch task (also a command or shell) will be skipped during check mode.  No actual changes should be made during check mode.  (Specifically, this means don't use 'check_mode: no' on any task that actually makes a change.)  An audit task that runs after a remediation to make sure it didn't go wrong should fail if a change cannot be validated, but should show as changed in the case of check_mode (indicating change needed) because the change won't have been applied.

3. Regarding tags, I propose to get rid of the 'patch' and 'audit' tags in favor of using ansible check mode.  For cat1, cat2, cat3, high, medium, and low tags, I propose removing them from each individual task and only having them on the include directive since the tags are inherited from an include task to all tasks included.  This would still require putting category and severity tags on tasks in prelim.yml.  I find tags to be very valuable to quickly run or exclude just a single task on the fly.

**Comment by jamescassell** [comment]
4. If a task makes a change, the output should show changed.  This means don't use 'changed_when: no' on a task that actually makes a change.

**Comment by shepdelacreme** [comment]
Ok so we will use: 
`name -> block -> task with name`

I think the task names still need to follow the standard naming convention though. i.e.
`"HIGH | RHEL-07-010010 | PATCH | The file permissions, ownership, and group membership of system files and commands must match the vendor values."`

Regarding point 2 - We went down this path with these roles previously (see the original RHEL6-STIG role) and we changed course away from it for several reasons.

1. It adds a significant amount of complexity and since you are using command/shell tasks and you have to write custom `changed_when` checks it can turn into complex, hacky, and hard to maintain code. 
1. We spent way too much time writing "audit" tasks and not enough time writing actual remediations. 

Our priority list for this role and other roles is:
- 100% remediation coverage. (For items that CAN feasibly be fixed automatically)
- 100% idempotent
- Automated tests and good coverage (see the RHEL7-CIS role for example of using Molecule test framework to validate remediations are doing what is intended/etc)
- Adding additional roles for other STIGs (OSes, server software, network devices, etc)
- Better/any documentation (generated with some sort of doc generator mkdocs, etc)
- check mode and diff support for remediations when using native Ansible Modules (if a module doesn't support check/diff properly then possibly looking at adding that support to the module upstream)
- check mode support for everything else

**Tags**
- I can get behind getting rid of `patch` and `audit` tags as they aren't really needed/used anymore.
- I think moving the cat 1,2,3 and high, medium, low tags makes sense.

For item 4 are there a lot of tasks that make changes with changed_when: no set? It shouldn't be that way. If command or shell is used for a **remediation** task it should have a custom `changed_when:` to properly report changes.

**Comment by shepdelacreme** [comment]
@jamescassell To clarify...I'm not saying we wouldn't appreciate additions that add check/diff functionality...just that my main priority is accurate and functional remediations.

**Comment by jamescassell** [comment]
Some of the times I mentioned may have been "my ideal" which might not line up with reality for everyone; I do try to follow it when making contributions, though.  Regarding tasks that make changes when changed_when: no is set, I haven't seen any in this role; it's just something I'm paranoid about as I've seen it in another role.

I'm a huge fan of adding remediations for other STIGs, in particular the PostgreSQL 9 STIG.

**Comment by jamescassell** [comment]
Do we care at all about satisfying the official DISA benchmark content?  One example where we meet the STIG requirement, but the benchmark fails is the weekly aide scan.  We use the "@weekly" special time, whereas the disa benchmark only recognizes traditional '* * * * * task" format, or files in /etc/cron.{daily,weekly,etc}.

**Comment by shepdelacreme** [comment]
Edited your comment because "@ weekly" without the space @ mentioned some random GH user.

As far as satisfying the DISA content...yes and no? I've been through enough CCRI's to know how literal the DISA auditors can be. In this instance I think we can update the task to have it drop in the daily or weekly cron folder. The only problem is this will cause a duplicate cron entry on systems that have run this role before.

**Comment by jamescassell** [comment]
I suppose we could leave a tombstone task to remove the existing cron entry, but that does clutter the role...

**Comment by mikerenfro** [comment]
I'm the new guy in terms of this area, but I'm leaning toward satisfy the STIG as written (clearly, given I rolled the disk and network audit checks into one task as written). Satisfying the intent of the STIG is better in theory, but I assume that just makes for more conversations with auditors of explaining how you satisfy a requirement when their script/tool returns a failure.

**Comment by jamescassell** [comment]
@shepdelacreme regarding tasks that make a change but don't report as such: RHEL-07-010240 RHEL-07-041010

**Comment by jamescassell** [comment]
Any opinions on whether we want to limit line lengths? If so, how long?

**Comment by shepdelacreme** [comment]
My personal preference is not to limit line length. With YAML/Ansible I prefer not to deal with an intentionally wrapped/continued line (I think it reduces clarity/readability). However I also work on very wide screens most the time and I am open to other opinions here.

**Comment by georgenalen** [comment]
Hello,
I wanted to reach out and let you know that this issue is being closed. We have re-worked the role and want to start with a fresh issues list with this latest version. There was a post in the Ansible-Lockdown google group (https://groups.google.com/g/ansible-lockdown) with the details of the changes that are coming. Please checkout the thread titled RHEL 7 CIS and STIG Changes for all of the details, I also have the message pasted at below.
Please as you use the latest version and open issue tickets as you find them, it is the best way for us to improve the role for everyone. Thank you for being part of the community and providing awareness of problems or advice on improvement. Reporting is a huge part of improving this project.

--------------------------------
Hello,
Thank you to everyone in the Ansible-Lockdown community who has contributed to RHEL7 STIG/CIS. Our team at MindPoint Group has been working with the entirety of the Ansible-Lockdown project, and we have some significant updates for both RHEL 7 STIG and CIS. With these updates, some larger changes have been made. I have these changes/updates outlined below.
Testing:
1.	CI/CD - We have implemented some automated testing pipelines to test pull requests into the devel and main branches. With the current workflow, the community will PR into the devel branch (never the main branch) for review by the administrators. When your PR is created, the first check will remain the DCO check. The second check is a functional testing pipeline that will automatically perform a functional test of the branch the PR is initiated from. Once both tests pass, someone from the Administrator Team will review the changes and merge them into the devel branch. From there, an additional review is completed before the devel branch is merged into the main branch. Only the Admin Team will perform PRs/merges into the main branch. There is also an automated pipeline for PRs from devel to main. Please do not edit the .github/workflows files since those are used as part of the pipeline.
2.	Compliance Checking – MindPoint Group has been working to create our own compliance audit scan tool. The tool uses a goss framework executable to run custom checks that we have created. The goal is to provide a more thorough check for control compliance and decrease the number of false positives/negatives. For example, it will check the configuration file related to the control and as well as checking if that configuration is active. With a smarter scan, we can hopefully identify attempts to trick scanners as well (for example stacking a parameter in a config file where the first instance is enabled and second disabled. Most audit tools search for the first instance but the application might look for the last instance of the parameter, thus making the scanning tool think it's enabled). In testing, we have found that our audit scan runs significantly faster than other audit tools, reducing audit times. Our audit tool and profiles will have their own repositories in the Ansible-Lockdown org, but within the remediation role there will be an integrated way to incorporate the audit. Keep an eye out for the audit tools as they are released. We plan on developing a goss audit profile for each current remediation role. Going forward, we plan to release a remediation role and goss audit tool profile simultaneously.
Role Updates:
1.	RHEL 7 STIG/CIS – We have re-written much of the RHEL 7 STIG and CIS roles to increase clarity and readability and address some functionality items. We performed these updates while creating our goss testing framework for each of these roles. We plan on pushing our update to the devel and main branches. We will move the current devel and master branches to a devel_stable_ and master_stable_ branch in the respective repositories. Accordingly, community members who rely on the current version can still use that version going forward; this process will not remove what is currently there. The latest versions of the roles have also been updated to comply with the latest benchmarks.
2.	Role Architecture – All roles will change with regard to the structure in the tasks folder. Taking CIS as an example, there will be a folder per section and yaml files for each sub-section. For example control 1.2.1 in CIS will be located in RHEL7-CIS/tasks/section_1/cis_1.2.x.yml. The cis_1.2.x.yml file will contain all controls related to section 1.2.x. This will hopefully make updates to roles a bit easier with less risk. This matches the architecture of our audit tool, creating consistency across remediation and audit platforms. The end goal is to repeat this architecture (the best we can) on STIG roles, but we are starting with CIS.
3.	Existing PRs and Issues – With all of these changes comes the task of cleaning up existing PR’s and issues. Our plan is to close all of the existing PR’s and issues because of the re-work. Our team is growing and should be able to stay on top of the new issues and PRs as they come in.
Again, I would like to thank the community for your involvement in this project. The input and work from the community has contributed significantly to the success of this project. Please keep an eye out for these changes, which will be rolling out in the coming weeks.
